In [49]:
#!/usr/bin/env python
import pandas as pd
import tensorflow as tf
import numpy as np
from numpy import genfromtxt
import plotly as plt

In [2]:
import sklearn

from sklearn import datasets
from sklearn.model_selection import train_test_split

In [3]:
Crime = pd.read_csv("/Users/chandanramanna/Downloads/CrimeData_Final.csv")
Crime.shape

(1954240, 26)

In [4]:
Crime[:10]

Unnamed: 0  Unnamed: 0.1        ID Case Number        Date  \
0           0            18  10500187    HZ241477  2016-04-26   
1           1            82  10500188    HZ241310  2016-04-26   
2           2           104  10500189    HZ241506  2016-04-26   
3           3           148  10500190    HZ241483  2016-04-26   
4           4           170  10500192    HZ241468  2016-04-26   
5           5           279  10500193    HZ241495  2016-04-26   
6           6           451  10500194    HZ240381  2016-04-26   
7           7           600  10500195    HZ241287  2016-04-26   
8           8           644  10500197    HZ241479  2016-04-26   
9           9           666  10500198    HZ241063  2016-04-26   

                  Block  IUCR        Primary Type  \
0       028XX E 95TH ST  1121  DECEPTIVE PRACTICE   
1  0000X W JACKSON BLVD  0810               THEFT   
2    054XX W MADISON ST  0820               THEFT   
3  013XX S LAWNDALE AVE  4387       OTHER OFFENSE   
4   048XX N KENMORE AVE  0810               THEFT   
5  074XX S EXCHANGE AVE  0486             BATTERY   
6    0000X W HUBBARD ST  0460             BATTERY   
7   007XX N AUSTIN BLVD  0320             ROBBERY   
8  070XX S EAST END AVE  0560             ASSAULT   
9  001XX S LAVERGNE AVE  0890               THEFT   

                   Description            Location Description  ...    \
0      COUNTERFEITING DOCUMENT                     GAS STATION  ...     
1                    OVER $500                        SIDEWALK  ...     
2               $500 AND UNDER  PARKING LOT/GARAGE(NON.RESID.)  ...     
3  VIOLATE ORDER OF PROTECTION                       APARTMENT  ...     
4                    OVER $500                          STREET  ...     
5      DOMESTIC BATTERY SIMPLE                        SIDEWALK  ...     
6                       SIMPLE                        SIDEWALK  ...     
7        STRONGARM - NO WEAPON                        SIDEWALK  ...     
8                       SIMPLE                       APARTMENT  ...     
9                FROM BUILDING                       RESIDENCE  ...     

   FBI Code  X Coordinate  Y Coordinate  Year              Updated On  \
0        10     1196846.0     1842514.0  2016  05/03/2016 03:51:27 PM   
1        06     1175785.0     1898975.0  2016  05/03/2016 03:51:27 PM   
2        06     1139904.0     1899485.0  2016  05/03/2016 03:51:27 PM   
3        26     1151918.0     1893645.0  2016  05/03/2016 03:51:27 PM   
4        06     1168378.0     1932431.0  2016  05/03/2016 03:51:27 PM   
5       08B     1194976.0     1856017.0  2016  05/03/2016 03:51:27 PM   
6       08B     1176165.0     1903315.0  2016  05/03/2016 03:51:27 PM   
7        03     1136246.0     1904116.0  2016  05/03/2016 03:51:27 PM   
8       08A     1188992.0     1858707.0  2016  05/03/2016 03:51:27 PM   
9        06     1143278.0     1899110.0  2016  05/03/2016 03:51:27 PM   

    Latitude  Longitude                       Location      Time  Month  
0  41.722725 -87.554566  (41.722725152, -87.554566354)  20:12:00      4  
1  41.878157 -87.630017  (41.878156557, -87.630017482)  09:00:00      4  
2  41.880287 -87.761753  (41.880287347, -87.761752861)  17:35:00      4  
3  41.864034 -87.717792  (41.864033702, -87.717792133)  20:32:00      4  
4  41.970125 -87.656244  (41.970124931, -87.656244114)  07:45:00      4  
5  41.759825 -87.560972    (41.759824717, -87.5609719)  21:00:00      4  
6  41.890057 -87.628491  (41.890057206, -87.628491342)  03:40:00      4  
7  41.893061 -87.775074   (41.89306149, -87.775074235)  18:01:00      4  
8  41.767352 -87.582817  (41.767351647, -87.582816839)  20:24:00      4  
9  41.879196 -87.749373   (41.87919597, -87.749373105)  14:53:00      4  

[10 rows x 26 columns]

In [6]:
#BURGLARY , THEFT
Crime = Crime.loc[Crime['Primary Type'].isin(["BURGLARY", "THEFT"]) ]

In [7]:
Crime[:3]

Unnamed: 0  Unnamed: 0.1        ID Case Number        Date  \
1           1            82  10500188    HZ241310  2016-04-26   
2           2           104  10500189    HZ241506  2016-04-26   
4           4           170  10500192    HZ241468  2016-04-26   

                  Block  IUCR Primary Type     Description  \
1  0000X W JACKSON BLVD  0810        THEFT       OVER $500   
2    054XX W MADISON ST  0820        THEFT  $500 AND UNDER   
4   048XX N KENMORE AVE  0810        THEFT       OVER $500   

             Location Description  ...    FBI Code  X Coordinate  \
1                        SIDEWALK  ...          06     1175785.0   
2  PARKING LOT/GARAGE(NON.RESID.)  ...          06     1139904.0   
4                          STREET  ...          06     1168378.0   

   Y Coordinate  Year              Updated On   Latitude  Longitude  \
1     1898975.0  2016  05/03/2016 03:51:27 PM  41.878157 -87.630017   
2     1899485.0  2016  05/03/2016 03:51:27 PM  41.880287 -87.761753   
4     1932431.0  2016  05/03/2016 03:51:27 PM  41.970125 -87.656244   

                        Location      Time  Month  
1  (41.878156557, -87.630017482)  09:00:00      4  
2  (41.880287347, -87.761752861)  17:35:00      4  
4  (41.970124931, -87.656244114)  07:45:00      4  

[3 rows x 26 columns]

In [8]:
Crime["Time"].apply(pd.to_datetime)

temp = pd.DatetimeIndex(Crime['Time'])
Crime['Hour'] = temp.hour

In [9]:
Crime["Date"].apply(pd.to_datetime)

temp = pd.DatetimeIndex(Crime['Date'])
Crime['Weekday'] = temp.weekday

In [10]:
Crime[:3]

Unnamed: 0  Unnamed: 0.1        ID Case Number        Date  \
1           1            82  10500188    HZ241310  2016-04-26   
2           2           104  10500189    HZ241506  2016-04-26   
4           4           170  10500192    HZ241468  2016-04-26   

                  Block  IUCR Primary Type     Description  \
1  0000X W JACKSON BLVD  0810        THEFT       OVER $500   
2    054XX W MADISON ST  0820        THEFT  $500 AND UNDER   
4   048XX N KENMORE AVE  0810        THEFT       OVER $500   

             Location Description   ...     Y Coordinate  Year  \
1                        SIDEWALK   ...        1898975.0  2016   
2  PARKING LOT/GARAGE(NON.RESID.)   ...        1899485.0  2016   
4                          STREET   ...        1932431.0  2016   

               Updated On   Latitude  Longitude  \
1  05/03/2016 03:51:27 PM  41.878157 -87.630017   
2  05/03/2016 03:51:27 PM  41.880287 -87.761753   
4  05/03/2016 03:51:27 PM  41.970125 -87.656244   

                        Location      Time  Month  Hour  Weekday  
1  (41.878156557, -87.630017482)  09:00:00      4     9        1  
2  (41.880287347, -87.761752861)  17:35:00      4    17        1  
4  (41.970124931, -87.656244114)  07:45:00      4     7        1  

[3 rows x 28 columns]

In [11]:
frame = Crime[["Year", "Month", "Hour", "Primary Type", "Weekday", "Community Area"]]

In [74]:
sample = frame[3:4]
sample

Year  Month  Hour Primary Type  Weekday  Community Area
9  2016      4    14        THEFT        1            25.0

In [ ]:
# frame = frame[:100000]
frame.shape

In [12]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

frame1 = frame.drop(['Primary Type'], axis=1)



In [13]:
for f in frame1.columns:
    if frame1[f].dtype == 'object':
        lbl_enc = LabelEncoder()
        # same as above encoding. it takes every object dtype from 
        # pandas dataframe and converts to numerical labels
        frame1[f] = lbl_enc.fit_transform(frame1[f].values)

frame1
X = frame1.values
X

array([[  2.01600000e+03,   4.00000000e+00,   9.00000000e+00,
          1.00000000e+00,   3.20000000e+01],
       [  2.01600000e+03,   4.00000000e+00,   1.70000000e+01,
          1.00000000e+00,   2.50000000e+01],
       [  2.01600000e+03,   4.00000000e+00,   7.00000000e+00,
          1.00000000e+00,   3.00000000e+00],
       ..., 
       [  2.01600000e+03,   4.00000000e+00,   1.40000000e+01,
          1.00000000e+00,   4.30000000e+01],
       [  2.01600000e+03,   4.00000000e+00,   7.00000000e+00,
          1.00000000e+00,   4.00000000e+01],
       [  2.01600000e+03,   4.00000000e+00,   1.90000000e+01,
          1.00000000e+00,   2.80000000e+01]])

In [14]:
X.shape

(558504, 5)

### creating the encode file

In [15]:
from sklearn import preprocessing
y = frame['Primary Type'].values
le = preprocessing.LabelEncoder()
le.fit(y)

LabelEncoder()

In [16]:
a = le.classes_
list(a)

['BURGLARY', 'THEFT']

In [17]:
y = le.transform(y)
le.fit(y)
b = le.classes_
list(b)

[0, 1]

In [18]:
Encoded_Mapping = pd.DataFrame(
    {'Encoded_output': b,
     'PrimaryTypes': a
    })
Encoded_Mapping

Encoded_output PrimaryTypes
0               0     BURGLARY
1               1        THEFT

In [19]:
y = frame['Primary Type'].values
# convert the labels from strings to numbers (0,1,2....)
y = LabelEncoder().fit_transform(y)
y

array([1, 1, 1, ..., 0, 0, 1])

In [20]:
np.unique(y)

array([0, 1])

In [21]:
y.shape

(558504,)

In [ ]:
def buildData():
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
    f=open('cs-training.csv','w')
    for i,j in enumerate(X_train):
        k=np.append(np.array(y_train[i]),j   )
        f.write(",".join([str(s) for s in k]) + '\n')
    f.close()
    f=open('cs-testing.csv','w')
    for i,j in enumerate(X_test):
        k=np.append(np.array(y_test[i]),j   )
        f.write(",".join([str(s) for s in k]) + '\n')
    f.close()

In [ ]:
# Convert to one hot
def convertOneHot(data):
    y=np.array([int(i[0]) for i in data])
    y_onehot=[0]*len(y)
    for i,j in enumerate(y):
        y_onehot[i]=[0]*(y.max() + 1)
        y_onehot[i][j]=1
    return (y,y_onehot)

In [ ]:
buildData()

In [ ]:
data = genfromtxt('cs-training.csv',delimiter=',')  # Training data
test_data = genfromtxt('cs-testing.csv',delimiter=',')  # Test data

In [ ]:
data[:3]

In [ ]:
test_data[:3]

In [ ]:
x_train=np.array([ i[1::] for i in data])
y_train,y_train_onehot = convertOneHot(data)

In [ ]:
x_test=np.array([ i[1::] for i in test_data])
y_test,y_test_onehot = convertOneHot(test_data)

In [22]:
# Specify that all features have real-value data
feature_columns = [tf.feature_column.numeric_column("x", shape=[5])]

In [23]:
feature_columns

[_NumericColumn(key='x', shape=(5,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [ ]:
tf.reset_default_graph()

In [ ]:
tf.logging.set_verbosity(tf.logging.INFO)

In [ ]:
feature_columns = tf.contrib.learn.infer_real_valued_columns_from_input(X_train)

In [40]:
# Build 3 layer DNN with 10, 20, 10 units respectively.
classifier = tf.contrib.learn.DNNClassifier(feature_columns=feature_columns,
                                          hidden_units=[6, 5, 2],
                                          n_classes=2,
                                           optimizer=tf.train.AdamOptimizer(
                                               learning_rate=0.001,
                                                beta1=0.9,
                                                beta2=0.999,
                                                epsilon=1e-08,
                                                use_locking=False,
                                                name='Adam'),
                                        activation_fn = tf.nn.relu,
                                        dropout = 0.02,
                                        model_dir = "/Users/chandanramanna/Deeplearning/ProjectNew/Model_File-1",
                                            config=tf.estimator.RunConfig().replace(save_summary_steps=10)
                                        
                                          )

TypeError: __init__() missing 1 required positional argument: 'feature_columns'

In [ ]:
TBcall=tf.train.SummarySaverHook(save_steps=10, output_dir='/Users/chandanramanna/Deeplearning/ProjectNew/TB', summary_op=tf.summary.merge_all())

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

In [28]:
np.unique(y_train)

array([0, 1])

In [29]:
# Define the training inputs
train_input_fn = tf.estimator.inputs.numpy_input_fn(
      x={"x": np.array(X_train)},
      y=np.array(y_train),
      num_epochs=None,
      shuffle=True)

In [ ]:
validation_monitor = tf.contrib.learn.monitors.ValidationMonitor(
    test_input_fn,
    every_n_steps=50)

In [ ]:
tf.train.SessionRunHook

In [30]:
X_train.shape

(374197, 5)

In [31]:
y_train.shape

(374197,)

In [ ]:

with SingularMonitoredSession(hooks=TBcall) as sess:
    
    while not sess.should_stop():
        sess.run(train_op)

In [32]:
train_op = classifier.fit(input_fn=train_input_fn, steps=2000)

Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /Users/chandanramanna/Deeplearning/ProjectNew/Model_File-1/model.ckpt.
INFO:tensorflow:loss = 197.964, step = 1
INFO:tensorflow:global_step/sec: 320.821
INFO:tensorflow:loss = 16.9252, step = 101 (0.310 sec)
INFO:tensorflow:global_step/sec: 331.753
INFO:tensorflow:loss = 0.686056, step = 201 (0.304 sec)
INFO:tensorflow:global_step/sec: 350.944
INFO:tensorflow:loss = 4.69311, step = 301 (0.283 sec)
INFO:tensorflow:global_step/sec: 344.386
INFO:tensorflow:loss = 0.979983, step = 401 (0.291 sec)
INFO:tensorflow:global_step/sec: 245.794
INFO:tensorflow:loss = 0.606595, step = 50

In [33]:
# Define the test inputs
test_input_fn = tf.estimator.inputs.numpy_input_fn(
      x={"x": np.array(X_test)},
      y=np.array(y_test),
      num_epochs=1,
      shuffle=False)

In [34]:
ev = classifier.evaluate(input_fn = test_input_fn, steps=1)

Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Starting evaluation at 2017-12-06-07:30:37
INFO:tensorflow:Restoring parameters from /Users/chandanramanna/Deeplearning/ProjectNew/Model_File-1/model.ckpt-2000
INFO:tensorflow:Evaluation [1/1]
INFO:tensorflow:Finished evaluation at 2017-12-06-07:30:38
INFO:tensorflow:Saving dict for global step 2000: accuracy = 0.757812, accuracy/baseline_label_mean = 0.757812, accuracy/threshold_0.500000_mean = 0.757812, auc = 0.5, auc_precision_recall = 0.878906, global_step = 2000, labels/actual_label_mean = 0.757812, labels/prediction_mean = 0.747643, loss = 0.553865, precision/positive_threshold_0.500000_mean = 0.757812, recall/positive_threshold_0.500000_mea

In [35]:
accuracy_score = classifier.evaluate(input_fn=test_input_fn)["accuracy"]

Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Starting evaluation at 2017-12-06-07:31:20
INFO:tensorflow:Restoring parameters from /Users/chandanramanna/Deeplearning/ProjectNew/Model_File-1/model.ckpt-2000
INFO:tensorflow:Finished evaluation at 2017-12-06-07:31:27
INFO:tensorflow:Saving dict for global step 2000: accuracy = 0.791375, accuracy/baseline_label_mean = 0.791375, accuracy/threshold_0.500000_mean = 0.791375, auc = 0.5, auc_precision_recall = 0.895688, global_step = 2000, labels/actual_label_mean = 0.791375, labels/prediction_mean = 0.747636, loss = 0.517412, precision/positive_threshold_0.500000_mean = 0.791375, recall/positive_threshold_0.500000_mean = 1.0


In [36]:
 print("\nTest Accuracy: {0:f}\n".format(accuracy_score))


Test Accuracy: 0.791375



In [44]:
predict_input_fn = tf.estimator.inputs.numpy_input_fn(
      x={"x": np.array(X_test)},
      num_epochs=1,
      shuffle=False)

In [45]:
predictions = classifier.predict(input_fn = predict_input_fn)

Instructions for updating:
Please switch to predict_classes, or set `outputs` argument.
INFO:tensorflow:Restoring parameters from /Users/chandanramanna/Deeplearning/ProjectNew/Model_File-1/model.ckpt-2000


## Cross validation  - KFold

In [64]:
from sklearn.model_selection import KFold # import KFold
X = np.array(X) # create an array
y = np.array(y) # Create another array
kf = KFold(n_splits=2) # Define the split - into 2 folds 
kf.get_n_splits(X) # returns the number of splitting iterations in the cross-validator
print(kf) 
KFold(n_splits=2, random_state=None, shuffle=False)

KFold(n_splits=2, random_state=None, shuffle=False)


KFold(n_splits=2, random_state=None, shuffle=False)

In [67]:
for train_index, test_index in kf.split(X):
    
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

TRAIN: [279252 279253 279254 ..., 558501 558502 558503] TEST: [     0      1      2 ..., 279249 279250 279251]
TRAIN: [     0      1      2 ..., 279249 279250 279251] TEST: [279252 279253 279254 ..., 558501 558502 558503]


In [68]:
# Necessary imports: 
from sklearn.cross_validation import cross_val_score, cross_val_predict
from sklearn import metrics

/Users/chandanramanna/anaconda/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning:

This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.



In [73]:
scores = cross_val_score(estimator=classifier,
X=X,
y=y,
scoring = 'accuracy',
cv=5,
fit_params={'steps': 1000},
)

TypeError: can't pickle _thread.lock objects

In [71]:
scores = cross_val_score(estimator=model,
X=iris.data,
y=iris.target,
scoring = 'accuracy',
cv=5,
fit_params={'steps': 1000},
)

TypeError: can't pickle _thread.lock objects

In [37]:
tf.summary.scalar('accuracy', accuracy_score)


<tf.Tensor 'accuracy:0' shape=() dtype=string>

In [ ]:
# Initialize and run
sess = tf.Session()
#sess = tf.InteractiveSession()
init = tf.initialize_all_variables()
sess.run(init)

In [ ]:
# Build the summary operation based on the TF collection of Summaries.
tf.train.write_graph(sess.graph_def,"/Users/chandanramanna/Deeplearning/ProjectNew/Model_File-1" ,'graph.pbtxt')

In [ ]:
tf.summary.scalar('accuracy', accuracy_score)
tf.summary.histogram('accuracy', accuracy_score)


In [ ]:
summary_op = tf.summary.merge_all()
#summary_writer = tf.train.SummaryWriter('./tenIrisSave/logs',graph_def=sess.graph_def)
summary_writer = tf.Summary.FileWriter("/Users/chandanramanna/Deeplearning/ProjectNew/Model_File-1/logs",sess.graph_def)

In [ ]:

merged = tf.summary.merge_all()
train_writer = tf.summary.FileWriter("/Users/chandanramanna/Deeplearning/ProjectNew/Model_File-1", sess.graph_def)
# test_writer = tf.summary.FileWriter("/Users/chandanramanna/Deeplearning/ProjectNew/test")


In [ ]:
tf.summary.scalar('loss', loss_calculated_in_the_graph)

### Test

In [75]:
sample

Year  Month  Hour Primary Type  Weekday  Community Area
9  2016      4    14        THEFT        1            25.0

In [76]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler

sample1 = sample.drop(['Primary Type'], axis=1)

In [77]:
for f in sample1.columns:
    if sample1[f].dtype == 'object':
        lbl_enc = LabelEncoder()
        # same as above encoding. it takes every object dtype from 
        # pandas dataframe and converts to numerical labels
        sample1[f] = lbl_enc.fit_transform(sample1[f].values)

sample1
X = sample1.values
X

array([[  2.01600000e+03,   4.00000000e+00,   1.40000000e+01,
          1.00000000e+00,   2.50000000e+01]])

In [78]:
new_samples = np.array( X , dtype=np.float32)
predict_input_fn = tf.estimator.inputs.numpy_input_fn(
      x={"x": new_samples},
      num_epochs=1,
      shuffle=False)

In [79]:
predictions = list(classifier.predict(input_fn=predict_input_fn))
predicted_classes = [p["classes"] for p in predictions]

Instructions for updating:
Please switch to predict_classes, or set `outputs` argument.
INFO:tensorflow:Restoring parameters from /Users/chandanramanna/Deeplearning/ProjectNew/Model_File-1/model.ckpt-2000


IndexError: invalid index to scalar variable.

In [ ]:
print(
      "New Samples, Class Predictions:    {}\n"
      .format(predicted_classes))

In [80]:
list(predictions)

[1]

### Regressor

In [ ]:
Regressor = tf.estimator.DNNRegressor(feature_columns=feature_columns,
                                          hidden_units=[6, 5, 5],
                                           optimizer=tf.train.AdamOptimizer(
                                               learning_rate=0.001,
                                                beta1=0.9,
                                                beta2=0.999,
                                                epsilon=1e-08,
                                                use_locking=False,
                                                name='Adam'),
                                        activation_fn = tf.nn.relu,
                                      
                                        )

In [ ]:
train_input_fn = tf.estimator.inputs.numpy_input_fn(
      x={"x": np.array(X_train)},
      y=np.array(y_train),
      num_epochs=None,
      shuffle=True)

In [ ]:
Regressor.fit(input_fn=input_fn_train)

In [ ]:
Regressor.evaluate(input_fn = test_input_fn)